export const REACT_APP_IMAGES_HOSTING = process.env.REACT_APP_IMAGES_HOSTING
export const REACT_APP_FACEBOOK_APP_ID = process.env.REACT_APP_FACEBOOK_APP_ID
export const REACT_APP_INSTAGRAM_CLIENT_ID =
  process.env.REACT_APP_INSTAGRAM_CLIENT_ID
